name: Mashwara Backend API

on:
  push:
    branches:
      - dev


jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [16.x]

    steps: 
      - uses: actions/checkout@v3
      - name: Use node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install

        env:
          CI: true

        with: 
          node-version: "14.x"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}

          run: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            . ~/.nvm/nvm.sh
            nvm install 16
            npm install -g pm2
            cd ~/mashwara-node-restapi
            git pull origin dev
            npm install
            npm run start


  deploy:
    # needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: actions/checkout@v2
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}

          script: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            . ~/.nvm/nvm.sh
            nvm install 16
            npm install -g pm2
            cd ~/mashwara-node-restapi
            git pull origin dev
            npm install
            npm run start
