name: Mashwara Backend API

on:
  push:
    branches:
      - dev


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [16.x]

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}

          script: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            . ~/.nvm/nvm.sh
            nvm install 16
            npm install -g pm2
            cd ~/mashwara-node-restapi
            git pull origin dev
            npm install
            npm run start
            pm2 restart app
